In [2]:
import numpy as np

#### Creating numpy arrays from list

In [8]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = a + b
print(c, type(c))

[5 7 9] <class 'numpy.ndarray'>


#### Comparing numpy addition with list addition

In [5]:
a1 = [1,2,3]
b1 = [4,5,6]
c1 = a1 + b1
c1

[1, 2, 3, 4, 5, 6]

### numpy arrays cannot contain elements with different types. If you try to build such a list, some of the elements' types are changed to end up with a homogeneous list. This is known as type coercion.


In [22]:
a2 = np.array([1,'1'])
a2

array(['1', '1'], dtype='<U21')

In [7]:
a3 = [1, '1']
a3

[1, '1']

#### Building a numpy array using some builtin function

In [14]:
height = np.random.normal(1.75, 0.20, 5000)
print(height)
height_r = np.round(height, 2)
print(height_r)

[1.89837112 2.27073555 1.88579698 ... 1.79528718 1.92735475 1.85088875]
[1.9  2.27 1.89 ... 1.8  1.93 1.85]


#### Basic statistics

In [15]:
weight = np.random.normal(60.5, 15, 5000)
weight_r = np.round(weight, 1)
weight_r

array([53.9, 45.7, 52.2, ..., 67.4, 75.7, 56. ])

In [17]:
np_bmi = np.column_stack((height_r, weight_r))
np_bmi

array([[ 1.9 , 53.9 ],
       [ 2.27, 45.7 ],
       [ 1.89, 52.2 ],
       ...,
       [ 1.8 , 67.4 ],
       [ 1.93, 75.7 ],
       [ 1.85, 56.  ]])

In [21]:
print(np.mean(weight_r), np.median(weight_r), np.std(weight_r))

60.92661999999999 61.0 15.017341754638203
